apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  annotations:
    notebooks.opendatahub.io/inject-oauth: 'true'
    notebooks.opendatahub.io/last-size-selection: Small
    notebooks.opendatahub.io/oauth-logout-url: https://rhods-dashboard-redhat-ods-applications.apps.jcollier-rhoaijul1521.devcluster.openshift.com/projects/rhtap-app?notebookLogout=test-jul15-6
    opendatahub.io/image-display-name: test-jul15-6
    opendatahub.io/username: 'kube:admin'
  name: test-jul15-6
  namespace: rhtap-app
  labels:
    app: test-jul15-6
    opendatahub.io/dashboard: 'true'
    opendatahub.io/odh-managed: 'true'
    opendatahub.io/user: kube-3aadmin
spec:
  template:
    spec:
      containers:
      - name: test-jul15-6
        image: image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/s2i-minimal-notebook:2024.1
        imagePullPolicy: Always
        env:
          - name: NOTEBOOK_ARGS
            value: |-
              --ServerApp.port=8888
              --ServerApp.token=''
              --ServerApp.password=''
              --ServerApp.base_url=/notebook/rhtap-app/test-jul15-6
              --ServerApp.quit_button=False
              --ServerApp.tornado_settings={"user":"kube-3aadmin","hub_host":"https://rhods-dashboard-redhat-ods-applications.apps.jcollier-rhoaijul1521.devcluster.openshift.com","hub_prefix":"/projects/rhtap-app"}
          - name: JUPYTER_IMAGE
            value: image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/s2i-minimal-notebook:2024.1
          - name: MODEL_ENDPOINT
            value: http://test-jul15-6-model-server.rhtap-app.svc.cluster.local:8001
          - name: MODEL_NAME
            value: "instructlab/granite-7b-lab"
        ports:
        - containerPort: 8888
          name: notebook-port
          protocol: TCP
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /notebook/rhtap-app/test-jul15-6/api
            port: notebook-port
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /notebook/rhtap-app/test-jul15-6/api
            port: notebook-port
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "2"
            memory: 8Gi
          requests:
            cpu: "1"
            memory: 8Gi
        volumeMounts:
        - mountPath: /opt/app-root/src
          name: test-jul15-6
        - mountPath: /dev/shm
          name: shm
        workingDir: /opt/app-root/src
      - name: oauth-proxy
        image: registry.redhat.io/openshift4/ose-oauth-proxy@sha256:4bef31eb993feb6f1096b51b4876c65a6fb1f4401fee97fa4f4542b6b7c9bc46
        imagePullPolicy: Always
        args:
        - --provider=openshift
        - --https-address=:8443
        - --http-address=
        - --openshift-service-account=test-jul15-6
        - --cookie-secret-file=/etc/oauth/config/cookie_secret
        - --cookie-expire=24h0m0s
        - --tls-cert=/etc/tls/private/tls.crt
        - --tls-key=/etc/tls/private/tls.key
        - --upstream=http://localhost:8888
        - --upstream-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        - --email-domain=*
        - --skip-provider-button
        - --openshift-sar={"verb":"get","resource":"notebooks","resourceAPIGroup":"kubeflow.org","resourceName":"test-jul15-6","namespace":"$(NAMESPACE)"}
        - --logout-url=https://rhods-dashboard-redhat-ods-applications.apps.jcollier-rhoaijul1521.devcluster.openshift.com/projects/rhtap-app?notebookLogout=test-jul15-6
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - containerPort: 8443
          name: oauth-proxy
          protocol: TCP
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /oauth/healthz
            port: oauth-proxy
            scheme: HTTPS
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /oauth/healthz
            port: oauth-proxy
            scheme: HTTPS
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 100m
            memory: 64Mi
          requests:
            cpu: 100m
            memory: 64Mi
        volumeMounts:
        - mountPath: /etc/oauth/config
          name: oauth-config
        - mountPath: /etc/tls/private
          name: tls-certificates
      enableServiceLinks: false
      serviceAccountName: test-jul15-6
      volumes:
      - name: test-jul15-6
        persistentVolumeClaim:
          claimName: test-jul15-6
      - emptyDir:
          medium: Memory
        name: shm
      - name: oauth-config
        secret:
          defaultMode: 420
          secretName: test-jul15-6-oauth-config
      - name: tls-certificates
        secret:
          defaultMode: 420
          secretName: test-jul15-6-tls